apiVersion: apps/v1
kind: Deployment
metadata:
  name: deepseek-vllm
  namespace: inference
  labels:
    app: deepseek-vllm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deepseek-vllm
  template:
    metadata:
      labels:
        app: deepseek-vllm
    spec:
      containers:
      - name: vllm
        image: vllm/vllm-openai:latest
        command: 
        - /bin/bash
        - -c
        - "vllm serve deepseek-ai/DeepSeek-R1-Distill-Llama-8B --max-model-len 2048"
        ports:
        - containerPort: 8000
          name: http
        resources:
          limits:
            cpu: "16"
            memory: "32G"
            nvidia.com/gpu: "1"
          requests:
            cpu: "8"
            memory: "32G"
            nvidia.com/gpu: "1"
      tolerations:
      - key: nvidia.com/gpu
        value: present
        effect: NoSchedule
      nodeSelector:
        karpenter.sh/nodepool: gpu-nodepool
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: karpenter.k8s.aws/instance-category
                operator: In
                values: ["g"]
              - key: karpenter.k8s.aws/instance-family
                operator: In
                values: ["g5", "g6"]
---
apiVersion: v1
kind: Service
metadata:
  name: deepseek-vllm
  namespace: inference
  labels:
    app: deepseek-vllm
spec:
  type: ClusterIP
  selector:
    app: deepseek-vllm
  ports:
  - port: 8000
    targetPort: 8000
    name: http 